apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: my-app-stack
data:
  DB_HOST: "database-1.c8tgmwkyk2mk.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "task_manager_db"
  JPA_DDL: "update"
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: my-app-stack
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: I0thYmlsMjkwMw==
