apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: my-app-stack
  labels:
    app: frontend
    tier: web
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: frontend
    env: v1
  ports:
    - name: http
      protocol: TCP
      port: 80  
      targetPort: frontend-port
